package com.example.demo;

public enum BombermanType {
    PLAYER, WALL, BRICK, BOMB, FLAME, DOOR,
    SPEED_ITEM, BOMB_ITEM, FLAME_ITEM,LIFE_ITEM,
    BRICK_BREAK, POWERUP_FLAMEPASS,
    BALLOOM_E, WATER_E, LANTERN_E,
    TIGER_E, CLOUD_E
}
