package com.example.demo;

public enum BombermanType {
    PLAYER, WALL, BRICK, BOMB, FLAME, DOOR,
    SPEED_ITEM, BOMB_ITEM, FLAME_ITEM,LIFE_ITEM,
    PORTAL, BRICK_BREAK, FLAME_PASS_ITEM,
    GRASS, CORAL, GRASS_BREAK, CORAL_BREAK,
    BALLOOM_E, WATER_E, LANTERN_E, WALL_BOMB,
    AROUND_WALL, TIGER_E, CLOUD_E, PASS_E,
    CHECK_FLAME, ENEMY_DIE;

}
